# fly.toml app configuration file generated for oumae-kumiko-bot on 2024-04-29T17:41:11+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oumae-kumiko-bot"
primary_region = "sin"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
